version: "3"

services:
  hucancode:
    image: hucancode
    build: .
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      # mount current dir into docker container
      - .:/hucancode
      # ignore local node_modules, use container
      - /hucancode/node_modules
      - /hucancode/.next